//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDoshico.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestDoshico.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avanti.
        /// </summary>
        public static string BtnAvanti {
            get {
                return ResourceManager.GetString("BtnAvanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cerca.
        /// </summary>
        public static string BtnCerca {
            get {
                return ResourceManager.GetString("BtnCerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fine.
        /// </summary>
        public static string BtnFine {
            get {
                return ResourceManager.GetString("BtnFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visualizza Grafico.
        /// </summary>
        public static string BtnGrafico {
            get {
                return ResourceManager.GetString("BtnGrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grafico Complessivo.
        /// </summary>
        public static string BtnGraficoComplessivo {
            get {
                return ResourceManager.GetString("BtnGraficoComplessivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indietro.
        /// </summary>
        public static string BtnIndietro {
            get {
                return ResourceManager.GetString("BtnIndietro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ritorna al Menù Principale.
        /// </summary>
        public static string BtnMenuPrincipale {
            get {
                return ResourceManager.GetString("BtnMenuPrincipale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva.
        /// </summary>
        public static string BtnSalva {
            get {
                return ResourceManager.GetString("BtnSalva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dati Cliente.
        /// </summary>
        public static string DatiCliente_Titolo {
            get {
                return ResourceManager.GetString("DatiCliente_Titolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a COSTITUZIONE:.
        /// </summary>
        public static string DatiPersonali_Costituzione {
            get {
                return ResourceManager.GetString("DatiPersonali_Costituzione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DATA:.
        /// </summary>
        public static string DatiPersonali_Data {
            get {
                return ResourceManager.GetString("DatiPersonali_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ETÀ:.
        /// </summary>
        public static string DatiPersonali_Eta {
            get {
                return ResourceManager.GetString("DatiPersonali_Eta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EVENTUALI NOTE:.
        /// </summary>
        public static string DatiPersonali_EvNote {
            get {
                return ResourceManager.GetString("DatiPersonali_EvNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EVENTUALE SQUILIBRIO:.
        /// </summary>
        public static string DatiPersonali_EvSquilibrio {
            get {
                return ResourceManager.GetString("DatiPersonali_EvSquilibrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INESTETISMI:.
        /// </summary>
        public static string DatiPersonali_Inestetismi {
            get {
                return ResourceManager.GetString("DatiPersonali_Inestetismi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SIG.RA:.
        /// </summary>
        public static string DatiPersonali_Signora {
            get {
                return ResourceManager.GetString("DatiPersonali_Signora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DATI PERSONALI.
        /// </summary>
        public static string DatiPersonali_Titolo {
            get {
                return ResourceManager.GetString("DatiPersonali_Titolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clienti Registrati a Sistema.
        /// </summary>
        public static string ListaClienti_Titolo {
            get {
                return ResourceManager.GetString("ListaClienti_Titolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test Registrati a Sistema.
        /// </summary>
        public static string ListaTests_Titolo {
            get {
                return ResourceManager.GetString("ListaTests_Titolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TIPO DOSHA.
        /// </summary>
        public static string Quesiti_DoshaHeader {
            get {
                return ResourceManager.GetString("Quesiti_DoshaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a KAPHA.
        /// </summary>
        public static string Quesiti_KaphaHeader {
            get {
                return ResourceManager.GetString("Quesiti_KaphaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PITTA.
        /// </summary>
        public static string Quesiti_PittaHeader {
            get {
                return ResourceManager.GetString("Quesiti_PittaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TOTALI PARZIALI.
        /// </summary>
        public static string Quesiti_Tot {
            get {
                return ResourceManager.GetString("Quesiti_Tot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VATA.
        /// </summary>
        public static string Quesiti_VataHeader {
            get {
                return ResourceManager.GetString("Quesiti_VataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CAPELLI IN FANCIULLEZZA.
        /// </summary>
        public static string QuesitiPt1_CapelliFanc {
            get {
                return ResourceManager.GetString("QuesitiPt1_CapelliFanc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ondulati, lisci e spessi.
        /// </summary>
        public static string QuesitiPt1_CapelliFancK {
            get {
                return ResourceManager.GetString("QuesitiPt1_CapelliFancK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fini e chiari.
        /// </summary>
        public static string QuesitiPt1_CapelliFancP {
            get {
                return ResourceManager.GetString("QuesitiPt1_CapelliFancP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Folti, attorcigliati e ricci.
        /// </summary>
        public static string QuesitiPt1_CapelliFancV {
            get {
                return ResourceManager.GetString("QuesitiPt1_CapelliFancV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a COLLO.
        /// </summary>
        public static string QuesitiPt1_Collo {
            get {
                return ResourceManager.GetString("QuesitiPt1_Collo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Largo e solido.
        /// </summary>
        public static string QuesitiPt1_ColloK {
            get {
                return ResourceManager.GetString("QuesitiPt1_ColloK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contenuto.
        /// </summary>
        public static string QuesitiPt1_ColloP {
            get {
                return ResourceManager.GetString("QuesitiPt1_ColloP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Piccolo.
        /// </summary>
        public static string QuesitiPt1_ColloV {
            get {
                return ResourceManager.GetString("QuesitiPt1_ColloV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CORPORATURA.
        /// </summary>
        public static string QuesitiPt1_Corporatura {
            get {
                return ResourceManager.GetString("QuesitiPt1_Corporatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CORPORATURA IN FANCIULLEZZA.
        /// </summary>
        public static string QuesitiPt1_CorporaturaFanc {
            get {
                return ResourceManager.GetString("QuesitiPt1_CorporaturaFanc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grossa e robusta.
        /// </summary>
        public static string QuesitiPt1_CorporaturaFancK {
            get {
                return ResourceManager.GetString("QuesitiPt1_CorporaturaFancK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Media.
        /// </summary>
        public static string QuesitiPt1_CorporaturaFancP {
            get {
                return ResourceManager.GetString("QuesitiPt1_CorporaturaFancP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esile.
        /// </summary>
        public static string QuesitiPt1_CorporaturaFancV {
            get {
                return ResourceManager.GetString("QuesitiPt1_CorporaturaFancV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grande o robusta.
        /// </summary>
        public static string QuesitiPt1_CorporaturaK {
            get {
                return ResourceManager.GetString("QuesitiPt1_CorporaturaK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Media e ben proporzionata.
        /// </summary>
        public static string QuesitiPt1_CorporaturaP {
            get {
                return ResourceManager.GetString("QuesitiPt1_CorporaturaP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Snella, a volte insolitamente alta o bassa.
        /// </summary>
        public static string QuesitiPt1_CorporaturaV {
            get {
                return ResourceManager.GetString("QuesitiPt1_CorporaturaV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DENTI.
        /// </summary>
        public static string QuesitiPt1_Denti {
            get {
                return ResourceManager.GetString("QuesitiPt1_Denti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grandi, spessi, bianchi e regolari con gengive rosa e morbide. Sani, non necessitano di cure.
        /// </summary>
        public static string QuesitiPt1_DentiK {
            get {
                return ResourceManager.GetString("QuesitiPt1_DentiK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Regolari con gengive rosa tendendi al sanguinamento e alle infiammazioni. Tendenza alle afte.
        /// </summary>
        public static string QuesitiPt1_DentiP {
            get {
                return ResourceManager.GetString("QuesitiPt1_DentiP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Irregolari, con gengive che nel tempo tendono a recedere, sensibili al freddo e al caldo, possono presentare ampi spazi fra un dente e l&apos;altro. Tendenza alle carie.
        /// </summary>
        public static string QuesitiPt1_DentiV {
            get {
                return ResourceManager.GetString("QuesitiPt1_DentiV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FRONTE.
        /// </summary>
        public static string QuesitiPt1_Fronte {
            get {
                return ResourceManager.GetString("QuesitiPt1_Fronte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spaziosa.
        /// </summary>
        public static string QuesitiPt1_FronteK {
            get {
                return ResourceManager.GetString("QuesitiPt1_FronteK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Media con pieghe e linee.
        /// </summary>
        public static string QuesitiPt1_FronteP {
            get {
                return ResourceManager.GetString("QuesitiPt1_FronteP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bassa.
        /// </summary>
        public static string QuesitiPt1_FronteV {
            get {
                return ResourceManager.GetString("QuesitiPt1_FronteV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MANI.
        /// </summary>
        public static string QuesitiPt1_Mani {
            get {
                return ResourceManager.GetString("QuesitiPt1_Mani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grandi, squadrate, morbide, tendenzialmente fredde o umide.
        /// </summary>
        public static string QuesitiPt1_ManiK {
            get {
                return ResourceManager.GetString("QuesitiPt1_ManiK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Proporzionate, nella media, tendenzialmente calde e morbide.
        /// </summary>
        public static string QuesitiPt1_ManiP {
            get {
                return ResourceManager.GetString("QuesitiPt1_ManiP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tendenzialmente ruvide, screpolate, piccole, affusolate, secche, fredde, nervose.
        /// </summary>
        public static string QuesitiPt1_ManiV {
            get {
                return ResourceManager.GetString("QuesitiPt1_ManiV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MENTO.
        /// </summary>
        public static string QuesitiPt1_Mento {
            get {
                return ResourceManager.GetString("QuesitiPt1_Mento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mascella larga.
        /// </summary>
        public static string QuesitiPt1_MentoK {
            get {
                return ResourceManager.GetString("QuesitiPt1_MentoK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contenuto.
        /// </summary>
        public static string QuesitiPt1_MentoP {
            get {
                return ResourceManager.GetString("QuesitiPt1_MentoP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delicato.
        /// </summary>
        public static string QuesitiPt1_MentoV {
            get {
                return ResourceManager.GetString("QuesitiPt1_MentoV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OCCHI.
        /// </summary>
        public static string QuesitiPt1_Occhi {
            get {
                return ResourceManager.GetString("QuesitiPt1_Occhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grandi, liquidi, con secrezioni. Calmi, blu o marrone chiaro, attraenti, a volte prominenti.
        /// </summary>
        public static string QuesitiPt1_OcchiK {
            get {
                return ResourceManager.GetString("QuesitiPt1_OcchiK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Medi, chiari, azzurri, grigi, verdi. Acuti e penetranti. Molto sensibili alla luce, si arrossano facilmente.
        /// </summary>
        public static string QuesitiPt1_OcchiP {
            get {
                return ResourceManager.GetString("QuesitiPt1_OcchiP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Piccoli, molto scuri, neri o blu. Possono essere diversi tra loro, asciutti. Hanno difficoltà a mantenere la concetrazione.
        /// </summary>
        public static string QuesitiPt1_OcchiV {
            get {
                return ResourceManager.GetString("QuesitiPt1_OcchiV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PELLE.
        /// </summary>
        public static string QuesitiPt1_Pelle {
            get {
                return ResourceManager.GetString("QuesitiPt1_Pelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Si abbronza uniformemente.
        /// </summary>
        public static string QuesitiPt1_PelleK {
            get {
                return ResourceManager.GetString("QuesitiPt1_PelleK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chiara, si scotta facilmente, sono comuni lentiggini e nei.
        /// </summary>
        public static string QuesitiPt1_PelleP {
            get {
                return ResourceManager.GetString("QuesitiPt1_PelleP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scura, si abbronza facilmente.
        /// </summary>
        public static string QuesitiPt1_PelleV {
            get {
                return ResourceManager.GetString("QuesitiPt1_PelleV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PRAKRITI.
        /// </summary>
        public static string QuesitiPt1_PrakritiHeader {
            get {
                return ResourceManager.GetString("QuesitiPt1_PrakritiHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a STRUTTURA OSSEA.
        /// </summary>
        public static string QuesitiPt1_StruttOssea {
            get {
                return ResourceManager.GetString("QuesitiPt1_StruttOssea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ossatura forte e solida, massiccio, quadrato, ben piantato e sviluppato. Peso consistente. Muscolatura massiccia che tollera sforzi.
        /// </summary>
        public static string QuesitiPt1_StruttOsseaK {
            get {
                return ResourceManager.GetString("QuesitiPt1_StruttOsseaK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ossatura armoniosa, peso equilibrato e costante. Muscolatura tonica e ben modellata.
        /// </summary>
        public static string QuesitiPt1_StruttOsseaP {
            get {
                return ResourceManager.GetString("QuesitiPt1_StruttOsseaP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ossa sottili e sporgenti, aspetti fisici disarmonici, magro. Muscolatura esile che si sviluppa con difficoltà.
        /// </summary>
        public static string QuesitiPt1_StruttOsseaV {
            get {
                return ResourceManager.GetString("QuesitiPt1_StruttOsseaV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TENDENZA DI ACCUMULO.
        /// </summary>
        public static string QuesitiPt1_TendAccumulo {
            get {
                return ResourceManager.GetString("QuesitiPt1_TendAccumulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sedere e cosce.
        /// </summary>
        public static string QuesitiPt1_TendAccumuloK {
            get {
                return ResourceManager.GetString("QuesitiPt1_TendAccumuloK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Uniforme.
        /// </summary>
        public static string QuesitiPt1_TendAccumuloP {
            get {
                return ResourceManager.GetString("QuesitiPt1_TendAccumuloP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Intorno alla vita.
        /// </summary>
        public static string QuesitiPt1_TendAccumuloV {
            get {
                return ResourceManager.GetString("QuesitiPt1_TendAccumuloV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ARTICOLAZIONI DOLORI TIPICI.
        /// </summary>
        public static string QuesitiPt2_Articolazioni {
            get {
                return ResourceManager.GetString("QuesitiPt2_Articolazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Flessibili, edematose, fortemente dolenti.
        /// </summary>
        public static string QuesitiPt2_ArticolazioniK {
            get {
                return ResourceManager.GetString("QuesitiPt2_ArticolazioniK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Calde, gonfie e che scottano.
        /// </summary>
        public static string QuesitiPt2_ArticolazioniP {
            get {
                return ResourceManager.GetString("QuesitiPt2_ArticolazioniP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Doloranti, malferme, scricchiolanti o rigide.
        /// </summary>
        public static string QuesitiPt2_ArticolazioniV {
            get {
                return ResourceManager.GetString("QuesitiPt2_ArticolazioniV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BIANCO DEGLI OCCHI (Sclera).
        /// </summary>
        public static string QuesitiPt2_BiancoOcchi {
            get {
                return ResourceManager.GetString("QuesitiPt2_BiancoOcchi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Con riflessi bluastri. Tendente ad avere occhi gonfi.
        /// </summary>
        public static string QuesitiPt2_BiancoOcchiK {
            get {
                return ResourceManager.GetString("QuesitiPt2_BiancoOcchiK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Può avere una tinta rossastra o giallastra.
        /// </summary>
        public static string QuesitiPt2_BiancoOcchiP {
            get {
                return ResourceManager.GetString("QuesitiPt2_BiancoOcchiP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tendente al grigio. Occhi spesso asciutti e pruriginosi.
        /// </summary>
        public static string QuesitiPt2_BiancoOcchiV {
            get {
                return ResourceManager.GetString("QuesitiPt2_BiancoOcchiV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CAPELLI.
        /// </summary>
        public static string QuesitiPt2_Capelli {
            get {
                return ResourceManager.GetString("QuesitiPt2_Capelli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spessi, leggermente ondulati, un po&apos; oleosi, scuri, marroni, splendenti.
        /// </summary>
        public static string QuesitiPt2_CapelliK {
            get {
                return ResourceManager.GetString("QuesitiPt2_CapelliK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fini, chiari, oleosi, biondi, rossi o precocemente grigi, sono possibili diradamento o calvizie precoce.
        /// </summary>
        public static string QuesitiPt2_CapelliP {
            get {
                return ResourceManager.GetString("QuesitiPt2_CapelliP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Secchi, opachi, con doppie punte, scuri, ruvidi, arricciati o crespi.
        /// </summary>
        public static string QuesitiPt2_CapelliV {
            get {
                return ResourceManager.GetString("QuesitiPt2_CapelliV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EVACUAZIONE.
        /// </summary>
        public static string QuesitiPt2_Evacuazione {
            get {
                return ResourceManager.GetString("QuesitiPt2_Evacuazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Una volta al giorno, abbondante, con possibile presenza di muco e prurito.
        /// </summary>
        public static string QuesitiPt2_EvacuazioneK {
            get {
                return ResourceManager.GetString("QuesitiPt2_EvacuazioneK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Possibile anche due-tre volte al giorno. Feci tendenti al molle.
        /// </summary>
        public static string QuesitiPt2_EvacuazioneP {
            get {
                return ResourceManager.GetString("QuesitiPt2_EvacuazioneP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Può essere irregolare con tendenza alla costipazione, Feci dure e asciutte.
        /// </summary>
        public static string QuesitiPt2_EvacuazioneV {
            get {
                return ResourceManager.GetString("QuesitiPt2_EvacuazioneV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GENGIVE.
        /// </summary>
        public static string QuesitiPt2_Gengive {
            get {
                return ResourceManager.GetString("QuesitiPt2_Gengive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sane e spesse.
        /// </summary>
        public static string QuesitiPt2_GengiveK {
            get {
                return ResourceManager.GetString("QuesitiPt2_GengiveK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Infiammate che tendono a sanguinare.
        /// </summary>
        public static string QuesitiPt2_GengiveP {
            get {
                return ResourceManager.GetString("QuesitiPt2_GengiveP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Che si ritraggono, lasciando scoperti i denti alla base.
        /// </summary>
        public static string QuesitiPt2_GengiveV {
            get {
                return ResourceManager.GetString("QuesitiPt2_GengiveV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INTERESSE SESSUALE.
        /// </summary>
        public static string QuesitiPt2_IntSessuale {
            get {
                return ResourceManager.GetString("QuesitiPt2_IntSessuale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stabile, lento ad eccitarsi.
        /// </summary>
        public static string QuesitiPt2_IntSessualeK {
            get {
                return ResourceManager.GetString("QuesitiPt2_IntSessualeK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Molto sensuale, si eccita facilmente.
        /// </summary>
        public static string QuesitiPt2_IntSessualeP {
            get {
                return ResourceManager.GetString("QuesitiPt2_IntSessualeP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Variabile, spazio alla fantasia.
        /// </summary>
        public static string QuesitiPt2_IntSessualeV {
            get {
                return ResourceManager.GetString("QuesitiPt2_IntSessualeV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LABBRA.
        /// </summary>
        public static string QuesitiPt2_Labbra {
            get {
                return ResourceManager.GetString("QuesitiPt2_Labbra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carnose e umettate.
        /// </summary>
        public static string QuesitiPt2_LabbraK {
            get {
                return ResourceManager.GetString("QuesitiPt2_LabbraK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rosso scuro con tendenza all&apos;herpes.
        /// </summary>
        public static string QuesitiPt2_LabbraP {
            get {
                return ResourceManager.GetString("QuesitiPt2_LabbraP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spesso screpolate.
        /// </summary>
        public static string QuesitiPt2_LabbraV {
            get {
                return ResourceManager.GetString("QuesitiPt2_LabbraV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LINGUA.
        /// </summary>
        public static string QuesitiPt2_Lingua {
            get {
                return ResourceManager.GetString("QuesitiPt2_Lingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tendenzialmente gonfia con una spessa patina biancastra.
        /// </summary>
        public static string QuesitiPt2_LinguaK {
            get {
                return ResourceManager.GetString("QuesitiPt2_LinguaK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Con patina giallastra oppure arancio-rossastra.
        /// </summary>
        public static string QuesitiPt2_LinguaP {
            get {
                return ResourceManager.GetString("QuesitiPt2_LinguaP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prevalentemente secca, con una leggera patina tendente al grigio.
        /// </summary>
        public static string QuesitiPt2_LinguaV {
            get {
                return ResourceManager.GetString("QuesitiPt2_LinguaV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MALATTIE RICORRENTI.
        /// </summary>
        public static string QuesitiPt2_Malattie {
            get {
                return ResourceManager.GetString("QuesitiPt2_Malattie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gonfiori, ritenzione di liquidi, muco e congestione.
        /// </summary>
        public static string QuesitiPt2_MalattieK {
            get {
                return ResourceManager.GetString("QuesitiPt2_MalattieK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Febbre, probabili le eruzioni cutanee e le infiammazioni.
        /// </summary>
        public static string QuesitiPt2_MalattieP {
            get {
                return ResourceManager.GetString("QuesitiPt2_MalattieP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dolori acuti e disturbi nervosi.
        /// </summary>
        public static string QuesitiPt2_MalattieV {
            get {
                return ResourceManager.GetString("QuesitiPt2_MalattieV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MESTRUAZIONI.
        /// </summary>
        public static string QuesitiPt2_Mestruazioni {
            get {
                return ResourceManager.GetString("QuesitiPt2_Mestruazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tendenza a ritenzione idrica durante il periodo.
        /// </summary>
        public static string QuesitiPt2_MestruazioniK {
            get {
                return ResourceManager.GetString("QuesitiPt2_MestruazioniK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abbondanti o molto abbondanti.
        /// </summary>
        public static string QuesitiPt2_MestruazioniP {
            get {
                return ResourceManager.GetString("QuesitiPt2_MestruazioniP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Irregolari, flusso scarso, crampi acuti e dolorosi.
        /// </summary>
        public static string QuesitiPt2_MestruazioniV {
            get {
                return ResourceManager.GetString("QuesitiPt2_MestruazioniV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PESO.
        /// </summary>
        public static string QuesitiPt2_Peso {
            get {
                return ResourceManager.GetString("QuesitiPt2_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Facilità a prendere peso e difficoltà a perderlo, se non si fa esercizio.
        /// </summary>
        public static string QuesitiPt2_PesoK {
            get {
                return ResourceManager.GetString("QuesitiPt2_PesoK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Facilità a prendere e perdere peso.
        /// </summary>
        public static string QuesitiPt2_PesoP {
            get {
                return ResourceManager.GetString("QuesitiPt2_PesoP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Facilità a perdere peso e difficoltà a riacquistarlo.
        /// </summary>
        public static string QuesitiPt2_PesoV {
            get {
                return ResourceManager.GetString("QuesitiPt2_PesoV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PREFERENZE LUOGHI.
        /// </summary>
        public static string QuesitiPt2_PrefLuoghi {
            get {
                return ResourceManager.GetString("QuesitiPt2_PrefLuoghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tollera la maggior parte dei climi (non ama l&apos;umidità).
        /// </summary>
        public static string QuesitiPt2_PrefLuoghiK {
            get {
                return ResourceManager.GetString("QuesitiPt2_PrefLuoghiK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preferisce i posti freschi e ben ventilati (non ama il calore).
        /// </summary>
        public static string QuesitiPt2_PrefLuoghiP {
            get {
                return ResourceManager.GetString("QuesitiPt2_PrefLuoghiP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non ama i climi ventosi e freddi (ama il calore).
        /// </summary>
        public static string QuesitiPt2_PrefLuoghiV {
            get {
                return ResourceManager.GetString("QuesitiPt2_PrefLuoghiV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TEMPERATURA.
        /// </summary>
        public static string QuesitiPt2_Temperatura {
            get {
                return ResourceManager.GetString("QuesitiPt2_Temperatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pelle fresca, umida, non fredda.
        /// </summary>
        public static string QuesitiPt2_TemperaturaK {
            get {
                return ResourceManager.GetString("QuesitiPt2_TemperaturaK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pelle calda al tatto.
        /// </summary>
        public static string QuesitiPt2_TemperaturaP {
            get {
                return ResourceManager.GetString("QuesitiPt2_TemperaturaP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mani e piedi freddi.
        /// </summary>
        public static string QuesitiPt2_TemperaturaV {
            get {
                return ResourceManager.GetString("QuesitiPt2_TemperaturaV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TENDENZE CIBO.
        /// </summary>
        public static string QuesitiPt2_TendCibo {
            get {
                return ResourceManager.GetString("QuesitiPt2_TendCibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ama dolci, latticini, pane e pasticceria.
        /// </summary>
        public static string QuesitiPt2_TendCiboK {
            get {
                return ResourceManager.GetString("QuesitiPt2_TendCiboK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ama cibi proteici, piccanti, speziati, salati, caffeina.
        /// </summary>
        public static string QuesitiPt2_TendCiboP {
            get {
                return ResourceManager.GetString("QuesitiPt2_TendCiboP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indulge ai cibi ricchi o alla dieta stretta.
        /// </summary>
        public static string QuesitiPt2_TendCiboV {
            get {
                return ResourceManager.GetString("QuesitiPt2_TendCiboV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TENDENZE PELLE (Spessore su avambraccio).
        /// </summary>
        public static string QuesitiPt2_TendPelle {
            get {
                return ResourceManager.GetString("QuesitiPt2_TendPelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ben lubrificata e spessa (2 cm o più).
        /// </summary>
        public static string QuesitiPt2_TendPelleK {
            get {
                return ResourceManager.GetString("QuesitiPt2_TendPelleK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Untuosa con tendenza ai brufoli e alle eruzioni (spessore da mezzo ad 1 cm).
        /// </summary>
        public static string QuesitiPt2_TendPelleP {
            get {
                return ResourceManager.GetString("QuesitiPt2_TendPelleP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Secca (circa mezzo cm, pizzicandola). Si screpola facilmente, propensione a calli e duroni.
        /// </summary>
        public static string QuesitiPt2_TendPelleV {
            get {
                return ResourceManager.GetString("QuesitiPt2_TendPelleV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VIKRITI.
        /// </summary>
        public static string QuesitiPt2_VikritiHeader {
            get {
                return ResourceManager.GetString("QuesitiPt2_VikritiHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AMICIZIA.
        /// </summary>
        public static string QuesitiPt3_Amicizia {
            get {
                return ResourceManager.GetString("QuesitiPt3_Amicizia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Leale, con molti amici.
        /// </summary>
        public static string QuesitiPt3_AmiciziaK {
            get {
                return ResourceManager.GetString("QuesitiPt3_AmiciziaK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Molto selettivo, crea salde amicizie e facilmente dei nemici.
        /// </summary>
        public static string QuesitiPt3_AmiciziaP {
            get {
                return ResourceManager.GetString("QuesitiPt3_AmiciziaP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conosce molte persone, pochi amici intimi.
        /// </summary>
        public static string QuesitiPt3_AmiciziaV {
            get {
                return ResourceManager.GetString("QuesitiPt3_AmiciziaV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CARATTERE.
        /// </summary>
        public static string QuesitiPt3_Carattere {
            get {
                return ResourceManager.GetString("QuesitiPt3_Carattere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Calmo, ama il rilassamento e le attività comode.
        /// </summary>
        public static string QuesitiPt3_CarattereK {
            get {
                return ResourceManager.GetString("QuesitiPt3_CarattereK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggressivo, preferisce le attività competitive.
        /// </summary>
        public static string QuesitiPt3_CarattereP {
            get {
                return ResourceManager.GetString("QuesitiPt3_CarattereP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Irrequieto, attivo, ama il movimento.
        /// </summary>
        public static string QuesitiPt3_CarattereV {
            get {
                return ResourceManager.GetString("QuesitiPt3_CarattereV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DECISIONI.
        /// </summary>
        public static string QuesitiPt3_Decisioni {
            get {
                return ResourceManager.GetString("QuesitiPt3_Decisioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ci mette tempo a prenderle, ma non le abbandona.
        /// </summary>
        public static string QuesitiPt3_DecisioniK {
            get {
                return ResourceManager.GetString("QuesitiPt3_DecisioniK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rapide da prendere, vede le cose chiaramente.
        /// </summary>
        public static string QuesitiPt3_DecisioniP {
            get {
                return ResourceManager.GetString("QuesitiPt3_DecisioniP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Difficili da prendere, cambia idea facilmente.
        /// </summary>
        public static string QuesitiPt3_DecisioniV {
            get {
                return ResourceManager.GetString("QuesitiPt3_DecisioniV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PSICOLOGIA DEL DENARO.
        /// </summary>
        public static string QuesitiPt3_Denaro {
            get {
                return ResourceManager.GetString("QuesitiPt3_Denaro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spende con riluttanza, gli piace risparmiare.
        /// </summary>
        public static string QuesitiPt3_DenaroK {
            get {
                return ResourceManager.GetString("QuesitiPt3_DenaroK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spende con criterio, il denaro ha lo scopo di realizzare la persona.
        /// </summary>
        public static string QuesitiPt3_DenaroP {
            get {
                return ResourceManager.GetString("QuesitiPt3_DenaroP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spende impulsivamente, il denaro è un mezzo e va usato.
        /// </summary>
        public static string QuesitiPt3_DenaroV {
            get {
                return ResourceManager.GetString("QuesitiPt3_DenaroV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MEMORIA.
        /// </summary>
        public static string QuesitiPt3_Memoria {
            get {
                return ResourceManager.GetString("QuesitiPt3_Memoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lento ad imparare, ma una volta imparato non dimentica più, iper logico e iper razionale.
        /// </summary>
        public static string QuesitiPt3_MemoriaK {
            get {
                return ResourceManager.GetString("QuesitiPt3_MemoriaK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Buona a breve ed a lungo termine, pensiero logico e razionale.
        /// </summary>
        public static string QuesitiPt3_MemoriaP {
            get {
                return ResourceManager.GetString("QuesitiPt3_MemoriaP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Buona a breve termine, ma dimentica facilmente. Concentrazione breve.
        /// </summary>
        public static string QuesitiPt3_MemoriaV {
            get {
                return ResourceManager.GetString("QuesitiPt3_MemoriaV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LA MENTE.
        /// </summary>
        public static string QuesitiPt3_MenteHeader {
            get {
                return ResourceManager.GetString("QuesitiPt3_MenteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ORGANIZZAZIONE.
        /// </summary>
        public static string QuesitiPt3_Organizzazione {
            get {
                return ResourceManager.GetString("QuesitiPt3_Organizzazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resiste ai cambiamenti ed ai nuovi progetti, ama la semplicità.
        /// </summary>
        public static string QuesitiPt3_OrganizzazioneK {
            get {
                return ResourceManager.GetString("QuesitiPt3_OrganizzazioneK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Costante, ama procedere in maniera ordinata.
        /// </summary>
        public static string QuesitiPt3_OrganizzazioneP {
            get {
                return ResourceManager.GetString("QuesitiPt3_OrganizzazioneP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fa molti progetti contemporaneamente.
        /// </summary>
        public static string QuesitiPt3_OrganizzazioneV {
            get {
                return ResourceManager.GetString("QuesitiPt3_OrganizzazioneV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PENSIERO.
        /// </summary>
        public static string QuesitiPt3_Pensiero {
            get {
                return ResourceManager.GetString("QuesitiPt3_Pensiero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preferisce seguire un piano od un&apos;idea.
        /// </summary>
        public static string QuesitiPt3_PensieroK {
            get {
                return ResourceManager.GetString("QuesitiPt3_PensieroK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Organizzato.
        /// </summary>
        public static string QuesitiPt3_PensieroP {
            get {
                return ResourceManager.GetString("QuesitiPt3_PensieroP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creativo.
        /// </summary>
        public static string QuesitiPt3_PensieroV {
            get {
                return ResourceManager.GetString("QuesitiPt3_PensieroV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ROUTINE.
        /// </summary>
        public static string QuesitiPt3_Routine {
            get {
                return ResourceManager.GetString("QuesitiPt3_Routine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lavora bene proprio seguendola.
        /// </summary>
        public static string QuesitiPt3_RoutineK {
            get {
                return ResourceManager.GetString("QuesitiPt3_RoutineK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ama pianificare ed organizzare.
        /// </summary>
        public static string QuesitiPt3_RoutineP {
            get {
                return ResourceManager.GetString("QuesitiPt3_RoutineP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non la ama.
        /// </summary>
        public static string QuesitiPt3_RoutineV {
            get {
                return ResourceManager.GetString("QuesitiPt3_RoutineV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EMOZIONI.
        /// </summary>
        public static string QuesitiPt4_EmozioniHeader {
            get {
                return ResourceManager.GetString("QuesitiPt4_EmozioniHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PUNTO DI FORZA CARATTERIALE.
        /// </summary>
        public static string QuesitiPt4_ForzCaratteriale {
            get {
                return ResourceManager.GetString("QuesitiPt4_ForzCaratteriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paziente.
        /// </summary>
        public static string QuesitiPt4_ForzCaratterialeK {
            get {
                return ResourceManager.GetString("QuesitiPt4_ForzCaratterialeK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tollerante.
        /// </summary>
        public static string QuesitiPt4_ForzCaratterialeP {
            get {
                return ResourceManager.GetString("QuesitiPt4_ForzCaratterialeP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Flessibile.
        /// </summary>
        public static string QuesitiPt4_ForzCaratterialeV {
            get {
                return ResourceManager.GetString("QuesitiPt4_ForzCaratterialeV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GESTIONE EMOZIONI.
        /// </summary>
        public static string QuesitiPt4_GestEmozioni {
            get {
                return ResourceManager.GetString("QuesitiPt4_GestEmozioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Devoto.
        /// </summary>
        public static string QuesitiPt4_GestEmozioniK {
            get {
                return ResourceManager.GetString("QuesitiPt4_GestEmozioniK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Si prende cura delle cose.
        /// </summary>
        public static string QuesitiPt4_GestEmozioniP {
            get {
                return ResourceManager.GetString("QuesitiPt4_GestEmozioniP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Comunicativo.
        /// </summary>
        public static string QuesitiPt4_GestEmozioniV {
            get {
                return ResourceManager.GetString("QuesitiPt4_GestEmozioniV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INDOLE.
        /// </summary>
        public static string QuesitiPt4_Indole {
            get {
                return ResourceManager.GetString("QuesitiPt4_Indole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Può essere trascurato.
        /// </summary>
        public static string QuesitiPt4_IndoleK {
            get {
                return ResourceManager.GetString("QuesitiPt4_IndoleK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Può essere vendicativo.
        /// </summary>
        public static string QuesitiPt4_IndoleP {
            get {
                return ResourceManager.GetString("QuesitiPt4_IndoleP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riservato.
        /// </summary>
        public static string QuesitiPt4_IndoleV {
            get {
                return ResourceManager.GetString("QuesitiPt4_IndoleV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ISTINTO.
        /// </summary>
        public static string QuesitiPt4_Istinto {
            get {
                return ResourceManager.GetString("QuesitiPt4_Istinto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Si sente vittima.
        /// </summary>
        public static string QuesitiPt4_IstintoK {
            get {
                return ResourceManager.GetString("QuesitiPt4_IstintoK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Può essere distruttivo.
        /// </summary>
        public static string QuesitiPt4_IstintoP {
            get {
                return ResourceManager.GetString("QuesitiPt4_IstintoP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Può essere autodistruttivo.
        /// </summary>
        public static string QuesitiPt4_IstintoV {
            get {
                return ResourceManager.GetString("QuesitiPt4_IstintoV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a REAZIONE EMOTIVA.
        /// </summary>
        public static string QuesitiPt4_ReazEmotiva {
            get {
                return ResourceManager.GetString("QuesitiPt4_ReazEmotiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Evita di esprimere opinioni in situazioni difficili.
        /// </summary>
        public static string QuesitiPt4_ReazEmotivaK {
            get {
                return ResourceManager.GetString("QuesitiPt4_ReazEmotivaK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggressivo riguardo le opinioni ed i sentimenti, esprime pareri anche se non richiesti.
        /// </summary>
        public static string QuesitiPt4_ReazEmotivaP {
            get {
                return ResourceManager.GetString("QuesitiPt4_ReazEmotivaP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I sentimenti e le emozioni cambiano facilmente.
        /// </summary>
        public static string QuesitiPt4_ReazEmotivaV {
            get {
                return ResourceManager.GetString("QuesitiPt4_ReazEmotivaV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a REAZIONE ALLO STRESS.
        /// </summary>
        public static string QuesitiPt4_ReazStress {
            get {
                return ResourceManager.GetString("QuesitiPt4_ReazStress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ha attaccamento alle cose.
        /// </summary>
        public static string QuesitiPt4_ReazStressK {
            get {
                return ResourceManager.GetString("QuesitiPt4_ReazStressK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Irritabile.
        /// </summary>
        public static string QuesitiPt4_ReazStressP {
            get {
                return ResourceManager.GetString("QuesitiPt4_ReazStressP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ansioso.
        /// </summary>
        public static string QuesitiPt4_ReazStressV {
            get {
                return ResourceManager.GetString("QuesitiPt4_ReazStressV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SENTIMENTO PREVALENTE.
        /// </summary>
        public static string QuesitiPt4_SentimentoPrev {
            get {
                return ResourceManager.GetString("QuesitiPt4_SentimentoPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apatia.
        /// </summary>
        public static string QuesitiPt4_SentimentoPrevK {
            get {
                return ResourceManager.GetString("QuesitiPt4_SentimentoPrevK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Odio.
        /// </summary>
        public static string QuesitiPt4_SentimentoPrevP {
            get {
                return ResourceManager.GetString("QuesitiPt4_SentimentoPrevP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paura.
        /// </summary>
        public static string QuesitiPt4_SentimentoPrevV {
            get {
                return ResourceManager.GetString("QuesitiPt4_SentimentoPrevV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SOGNI.
        /// </summary>
        public static string QuesitiPt4_Sogni {
            get {
                return ResourceManager.GetString("QuesitiPt4_Sogni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Corti e romantici, spesso riguardante l&apos;acqua.
        /// </summary>
        public static string QuesitiPt4_SogniK {
            get {
                return ResourceManager.GetString("QuesitiPt4_SogniK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Colorati, veloci, passionali, conflittuali.
        /// </summary>
        public static string QuesitiPt4_SogniP {
            get {
                return ResourceManager.GetString("QuesitiPt4_SogniP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Agitati, incubi, sogna di volare.
        /// </summary>
        public static string QuesitiPt4_SogniV {
            get {
                return ResourceManager.GetString("QuesitiPt4_SogniV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TENDENZA EMOZIONALE.
        /// </summary>
        public static string QuesitiPt4_TendEmozionale {
            get {
                return ResourceManager.GetString("QuesitiPt4_TendEmozionale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Desideroso.
        /// </summary>
        public static string QuesitiPt4_TendEmozionaleK {
            get {
                return ResourceManager.GetString("QuesitiPt4_TendEmozionaleK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rabbioso.
        /// </summary>
        public static string QuesitiPt4_TendEmozionaleP {
            get {
                return ResourceManager.GetString("QuesitiPt4_TendEmozionaleP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nervoso.
        /// </summary>
        public static string QuesitiPt4_TendEmozionaleV {
            get {
                return ResourceManager.GetString("QuesitiPt4_TendEmozionaleV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VIRTÙ.
        /// </summary>
        public static string QuesitiPt4_Virtù {
            get {
                return ResourceManager.GetString("QuesitiPt4_Virtù", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Armonioso.
        /// </summary>
        public static string QuesitiPt4_VirtùK {
            get {
                return ResourceManager.GetString("QuesitiPt4_VirtùK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Percettivo.
        /// </summary>
        public static string QuesitiPt4_VirtùP {
            get {
                return ResourceManager.GetString("QuesitiPt4_VirtùP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dinamico.
        /// </summary>
        public static string QuesitiPt4_VirtùV {
            get {
                return ResourceManager.GetString("QuesitiPt4_VirtùV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VIZIO.
        /// </summary>
        public static string QuesitiPt4_Vizio {
            get {
                return ResourceManager.GetString("QuesitiPt4_Vizio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avido.
        /// </summary>
        public static string QuesitiPt4_VizioK {
            get {
                return ResourceManager.GetString("QuesitiPt4_VizioK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manipolatore.
        /// </summary>
        public static string QuesitiPt4_VizioP {
            get {
                return ResourceManager.GetString("QuesitiPt4_VizioP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vile.
        /// </summary>
        public static string QuesitiPt4_VizioV {
            get {
                return ResourceManager.GetString("QuesitiPt4_VizioV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cliente già Registrato:.
        /// </summary>
        public static string SelezionaClienteEsistente {
            get {
                return ResourceManager.GetString("SelezionaClienteEsistente", resourceCulture);
            }
        }
    }
}
